# fly.toml app configuration file generated for hypergraph on 2025-06-27T09:23:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hypergraph'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3030
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
