packages:
  - apps/*
  - apps/*/*
  - packages/*
  - docs
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@reown/appkit'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - bufferutil
  - cbor-extract
  - core-js
  - core-js-pure
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
  - utf-8-validate
