packages:
  - apps/*
  - packages/*
  - docs

onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - better-sqlite3
  - core-js
  - core-js-pure
  - prisma
  - ./test3
  - ./test4
  - ./test5
  - ./test6
