/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthenticateCallbackRouteImport } from './routes/authenticate-callback';
import { Route as IndexRouteImport } from './routes/index';

const AuthenticateCallbackRoute = AuthenticateCallbackRouteImport.update({
  id: '/authenticate-callback',
  path: '/authenticate-callback',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/authenticate-callback': typeof AuthenticateCallbackRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/authenticate-callback': typeof AuthenticateCallbackRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/authenticate-callback': typeof AuthenticateCallbackRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/authenticate-callback';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/authenticate-callback';
  id: '__root__' | '/' | '/authenticate-callback';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticateCallbackRoute: typeof AuthenticateCallbackRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/authenticate-callback': {
      id: '/authenticate-callback';
      path: '/authenticate-callback';
      fullPath: '/authenticate-callback';
      preLoaderRoute: typeof AuthenticateCallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticateCallbackRoute: AuthenticateCallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
