/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as SpaceSpaceIdImport } from './routes/space/$spaceId'
import { Route as SettingsExportWalletImport } from './routes/settings/export-wallet'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SpaceSpaceIdRoute = SpaceSpaceIdImport.update({
  id: '/space/$spaceId',
  path: '/space/$spaceId',
  getParentRoute: () => rootRoute,
} as any)

const SettingsExportWalletRoute = SettingsExportWalletImport.update({
  id: '/settings/export-wallet',
  path: '/settings/export-wallet',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/settings/export-wallet': {
      id: '/settings/export-wallet'
      path: '/settings/export-wallet'
      fullPath: '/settings/export-wallet'
      preLoaderRoute: typeof SettingsExportWalletImport
      parentRoute: typeof rootRoute
    }
    '/space/$spaceId': {
      id: '/space/$spaceId'
      path: '/space/$spaceId'
      fullPath: '/space/$spaceId'
      preLoaderRoute: typeof SpaceSpaceIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/settings/export-wallet': typeof SettingsExportWalletRoute
  '/space/$spaceId': typeof SpaceSpaceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/settings/export-wallet': typeof SettingsExportWalletRoute
  '/space/$spaceId': typeof SpaceSpaceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginLazyRoute
  '/settings/export-wallet': typeof SettingsExportWalletRoute
  '/space/$spaceId': typeof SpaceSpaceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/settings/export-wallet' | '/space/$spaceId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/settings/export-wallet' | '/space/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings/export-wallet'
    | '/space/$spaceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginLazyRoute: typeof LoginLazyRoute
  SettingsExportWalletRoute: typeof SettingsExportWalletRoute
  SpaceSpaceIdRoute: typeof SpaceSpaceIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginLazyRoute: LoginLazyRoute,
  SettingsExportWalletRoute: SettingsExportWalletRoute,
  SpaceSpaceIdRoute: SpaceSpaceIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/settings/export-wallet",
        "/space/$spaceId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/settings/export-wallet": {
      "filePath": "settings/export-wallet.tsx"
    },
    "/space/$spaceId": {
      "filePath": "space/$spaceId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
