import { createFunctions, type } from "graph-framework";

// this is autogenerated
// const spaceTypes = {
//   iban: S.Text,
// };

// const spaceAttributes = {
//   iban: spaceTypes.Iban,
//   age: type.Number,
//   isActive: type.Checkbox,
//   email: type.Text,
// };

// end autogenerated

export const schema = {
  attributes: {
    // ...spaceAttributes,
    name: type.Text,
    age: type.Number,
    isActive: type.Checkbox,
    email: type.Text,
  },
  relations: {
    // friends: type.Relation(["User", "Person"], {
    //   cardinality: "many", // "one" | "many"
    // }),
    // soulmate: type.Relation(["User", "Person"], {
    //   cardinality: "one", // "one" | "many"
    // }),
  },
  types: {
    Person: ["name", "age"] as const,
    User: ["name", "email"] as const,
    Event: ["name"] as const,
  },
  // imports: {
  //   attributes: {},
  //   types: {
  //     Animal: "abcd",
  //   },
  //   relations: {
  //     owner: "xyz",
  //   },
  // },
};

export const {
  SpaceProvider,
  useCreateEntity,
  useDeleteEntity,
  useSpaceId,
  createDocumentId,
  useQuery,
} = createFunctions(schema);
