/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AppsCreateImport } from './routes/apps/create'
import { Route as AppsAppIdDetailsImport } from './routes/apps/$appId/details'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppsCreateRoute = AppsCreateImport.update({
  id: '/apps/create',
  path: '/apps/create',
  getParentRoute: () => rootRoute,
} as any)

const AppsAppIdDetailsRoute = AppsAppIdDetailsImport.update({
  id: '/apps/$appId/details',
  path: '/apps/$appId/details',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/apps/create': {
      id: '/apps/create'
      path: '/apps/create'
      fullPath: '/apps/create'
      preLoaderRoute: typeof AppsCreateImport
      parentRoute: typeof rootRoute
    }
    '/apps/$appId/details': {
      id: '/apps/$appId/details'
      path: '/apps/$appId/details'
      fullPath: '/apps/$appId/details'
      preLoaderRoute: typeof AppsAppIdDetailsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/create': typeof AppsCreateRoute
  '/apps/$appId/details': typeof AppsAppIdDetailsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/create': typeof AppsCreateRoute
  '/apps/$appId/details': typeof AppsAppIdDetailsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/apps/create': typeof AppsCreateRoute
  '/apps/$appId/details': typeof AppsAppIdDetailsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps/create' | '/apps/$appId/details'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apps/create' | '/apps/$appId/details'
  id: '__root__' | '/' | '/apps/create' | '/apps/$appId/details'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsCreateRoute: typeof AppsCreateRoute
  AppsAppIdDetailsRoute: typeof AppsAppIdDetailsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsCreateRoute: AppsCreateRoute,
  AppsAppIdDetailsRoute: AppsAppIdDetailsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/apps/create",
        "/apps/$appId/details"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/apps/create": {
      "filePath": "apps/create.tsx"
    },
    "/apps/$appId/details": {
      "filePath": "apps/$appId/details.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
